openapi: "3.0.3"
info:
  version: 0.0.1
  title: AuctionHouse
servers:
  - url: http://localhost:{port}/api
    variables:
      port:
        enum:
          - '8000'
        default: '8000'
paths:
  /bid:
    post:
      summary: Add a bid to an item.
      operationId: addBid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddBidRequest'
      responses:
        "201":
          description: Added bid.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    AddBidRequest:
      properties:
        itemId:
          type: number
          format: int64
        bidPrice:
          type: string
      required:
        - itemId
        - bidPrice
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
